#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Compare each <stem>.hex on disk with words emitted by gen_extra_tests.PROGRAMS."""
from pathlib import Path

import gen_extra_tests as g


def read_hex(path: Path):
    lines = path.read_text(encoding="ascii", errors="replace").strip().split()
    return [int(x, 16) for x in lines if x]


def main():
    root = Path(__file__).resolve().parent
    bad = []
    ok = []
    for stem, words in sorted(g.PROGRAMS.items()):
        path = root / f"{stem}.hex"
        if not path.exists():
            bad.append((stem, "missing file"))
            continue
        got = read_hex(path)
        if got != words:
            bad.append((stem, f"len got={len(got)} exp={len(words)}"))
            for i, (a, b) in enumerate(zip(got, words)):
                if a != b:
                    bad.append((stem, f"  word[{i}] got={a:08x} exp={b:08x}"))
                    break
            if len(got) != len(words):
                pass
        else:
            ok.append(stem)

    manual = sorted(
        p.stem
        for p in root.glob("t*.hex")
        if p.stem not in g.PROGRAMS and p.name != "code.hex"
    )

    print("PROGRAMS: OK", len(ok), "/", len(g.PROGRAMS))
    for s in ok:
        print("  OK", s)
    if bad:
        print("MISMATCH / ERROR:")
        for row in bad:
            print(" ", row)
    else:
        print("All PROGRAMS .hex files match generator.")

    print("\nNot generated by gen_extra_tests.py (maintain separately):", len(manual))
    for s in manual:
        print(" ", s)


if __name__ == "__main__":
    main()
